Test of minimal action

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -61,12 +61,43 @@ jobs:
             exit 1
           fi
 
-      # If `dist/` was different than expected, upload the expected version as a
-      # workflow artifact.
-      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
-        id: upload
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+  check-minimal-dist:
+    name: Check minimal/dist/
+    runs-on: ubuntu-slim
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+
+      - name: Setup Node.js
+        id: setup-node
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
-          name: dist
-          path: dist/
+          node-version-file: 'minimal/package.json'
+          cache: npm
+
+      - name: Install Dependencies
+        id: install
+        run: npm ci
+        working-directory: minimal
+
+      - name: Build minimal/dist/ Directory
+        id: build
+        run: npm run bundle
+        working-directory: minimal
+
+      # This will fail the workflow if the `minimal/dist/` directory is different than
+      # expected.
+      - name: Compare Directories
+        run: |
+          if [ ! -d minimal/dist/ ]; then
+            echo "Expected minimal/dist/ directory does not exist.  See status below:"
+            ls -la ./minimal/
+            exit 1
+          fi
+          if [ "$(git diff --ignore-space-at-eol --text minimal/dist/ | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build. See status below:"
+            git diff --ignore-space-at-eol --text minimal/dist/
+            exit 1
+          fi
